### ISSUE TITLE
TypeError

### ISSUE THREAD

**Issue by Carpy444** [Blackened76/SWGoH-Squad-Builder#2]
Every time refresh is pressed after inputting Swgoh.gg details and giving the script permission to run the following error is presented

TypeError: Cannot read property "members" from undefined.

The doc then doesn't draw anything from the API.

**Comment by Carpy444** [comment]
After starting fresh and restarting Docs a new error has replaced this one.

Error when retreiving data from swgoh.gg API
SyntaxError: Unexpected token: <

My apologies if I'm not providing enough detail or these are easily manageable, I'm not too savvy at this!

**Comment by Blackened76** [comment]
Hey Carpy, can you please copy the latest version of the sheet and let me know if you have the same issue?  This issue may have been corrected since it was opened, but just to be sure.  If you still have the same problem, let me know and I'll try to walk through it with you.  Thanks!
[SWGoH Squad Builder](https://drive.google.com/drive/folders/188RBXySdpUciG4mRRc8WwX8TH_UbZxJA?usp=sharing)

**Comment by Blackened76** [comment]
@Carpy444 Since I haven't heard back on this, I'm going to go ahead and close this issue.  If you continue to have issues with the sheet, you can create a new issue.  Just make sure you're using the latest copy of the sheet found here...
[SWGoH Squad Builder](https://drive.google.com/drive/folders/188RBXySdpUciG4mRRc8WwX8TH_UbZxJA?usp=sharing)

Thanks!
